### ISSUE TITLE
Support for Patch 7.3 (Empyrium)

### ISSUE THREAD

**Issue by Demonid** [ls-/ls_Prospector#2]
Will you add support for Empyrium? Thanks!

**Comment by ls-** [comment]
But why?

Gem weaving doesn't even exist in this case, all chips are always colourless, honestly, I just mass prospect it.

**Comment by Demonid** [comment]
My bad, i realized that they didn't added the chip prospect method to the new ores some hours after posting this.

Closing this and thanks for your answer 👍
